### ISSUE TITLE
Error in $:/themes/nico/notebook/ui/Sidebar/Sections

### ISSUE THREAD

**Issue by danraymond** [NicolasPetton/Projectify#18]
@NicolasPetton the list filter contains the word "daft" of instead of "draft" of:

<$list filter="[all[shadows+tiddlers]!has[daft.of]tag[$:/themes/nico/notebook/tags/SidebarSection]]">
  {{||$:/themes/nico/notebook/ui/Sidebar/SectionTemplate}}
</$list>

**Comment by NicolasPetton** [comment]
Thanks, I'll move the ticket to the notebook project.

**Comment by NicolasPetton** [comment]
I moved it to https://github.com/NicolasPetton/Notebook/issues/18
