### ISSUE TITLE
Due date assignment wrong

### ISSUE THREAD

**Issue by ludwa6** [NicolasPetton/Projectify#21]
As described in [this TW Users group thread](https://groups.google.com/u/1/g/tiddlywiki/c/D0iGR1pAyeQ), having just yesterday installed Projectify v0.9 and scheduled my first couple of ToDo items using the "Tomorrow" button, i was surprised this morning (i.e. "tomorrow" :-) to find that these two ToDos were red-flagged as 42 days overdue... And even more surprised after a couple hours work on other tiddlers (nothing related to these two, nor to the system) to find that they are now flagged as just 21 hours overdue, and with due-date of 20210110120000000 (closer, but is still wrong -even earlier than the create date on the tiddlers).

**Comment by NicolasPetton** [comment]
Thanks fo reporting this @ludwa6.

If you set them for today, then the due date of `20210110120000000` is expected (The date is set on the day, with the time set to 12:00). They should be marked in the UI as "Today" though, not overdue.

Can you tell me which timezone you're in?

I'm quite concerned by the 42 days shift. Did it disappear without you changing their due date?

**Comment by ludwa6** [comment]
I'm in Portugal (WET -same as GMT now), and this is is the 11th of January (2021.01.11), so that datetimestamp set yesterday for "Tomorrow" should have had a 1 for its 8th digit, not a 0. 

And to your other Q: yes, the "42 days overdue" warning changed to "21 hours overdue" without my changing anything related to these tiddlers. Of course one can only thing i did *something* to trigger such a change -and i was indeed working in TW during the interval- but i'm quite sure i changed nothing on these two tiddlers.

**Comment by NicolasPetton** [comment]
@ludwa6 thanks for the infos.

If you set a due date to tomorrow again, does it appear to work? What about after reloading the browser tab?

**Comment by ludwa6** [comment]
OK @NicolasPetton i reset the due date, using "Tomorrow" button, and now it shows 20210112120000000 -even after save and reload of TiddlyDesktop. 

So: this issue may have been ephemeral, but i'm gonna lean into Projectify the next few hours, and we'll see if this problem reappears, before calling this issue closed.

**Comment by NicolasPetton** [comment]
> So: this issue may have been ephemeral, but i'm gonna lean into Projectify the next few hours, and we'll see if this problem reappears, before calling this issue closed.

I found out what the problem was, it's a bug in the calendar picker with the keyboard navigation. 
I'll push a fix and will release a new version tonight!
