### ISSUE TITLE
French translation missing string

### ISSUE THREAD

**Issue by silvyn** [NicolasPetton/Projectify#28]
Hello,

Notice this few missing string : 

<img width="296" alt="Capture d’écran 2021-01-20 à 21 40 01" src="https://user-images.githubusercontent.com/9981592/105242454-61300800-5b6e-11eb-8662-780d01fb20a6.png">

* Title tag hover

<img width="511" alt="Capture d’écran 2021-01-20 à 21 40 40" src="https://user-images.githubusercontent.com/9981592/105242716-84f34e00-5b6e-11eb-90a6-cb723ddac37f.png">

* Reorder projects (Réordonner les projets)

<img width="384" alt="Capture d’écran 2021-01-20 à 21 41 39" src="https://user-images.githubusercontent.com/9981592/105242903-963c5a80-5b6e-11eb-8929-05343624055d.png">

* Archiver ce projet

**Comment by silvyn** [comment]
Définir **la** catégorie : 

<img width="356" alt="Capture d’écran 2021-01-20 à 22 59 48" src="https://user-images.githubusercontent.com/9981592/105246250-42804000-5b73-11eb-9648-93be388c4db7.png">

**Comment by silvyn** [comment]
Found some of them in index.multids, just edit with GitHub :)

**Comment by NicolasPetton** [comment]
I saw that, thanks for the PR!
