### ISSUE TITLE
Strange Click Behavior

### ISSUE THREAD

**Issue by streaml1ne555** [NicolasPetton/Projectify#36]
I followed the installation guide to add Projectify to my TW but I'm seeing some strange click behavior on tasks. First the layout looks incorrect with the checkbox, task description, and click and drag anchor on separate lines.

![projectify_formatting_issue](https://user-images.githubusercontent.com/9360873/105941860-596bda00-602c-11eb-86df-20d7d983169f.png)

Secondly if I click anywhere in the task's box it marks it as complete. I'm using Firefox and the demo site seems to work fine. It seems like there is some bad interaction with this plugin:

https://ibnishak.github.io/Tesseract/projects/tekan/Tekan.html

If I disable it things work as expected and as they do on the demo. Ideally I'd like to keep this plugin around, but I'm not sure why they conflict.

**Comment by NicolasPetton** [comment]
Hi! Unfortunately the Tekan plugin applies some styles on all elements of the page, without any scoping, which can impact other plugins negatively.

I could try to add hacks to Projectify to counteract the problem, but it would be hard to guarantee that everything would work.

**Comment by streaml1ne555** [comment]
I guess we can close this then, hacky fixes are no good and after using Projectify more I'm thinking I can probably get rid of Tekan and adapt to Projectify fully. Will open a new issue with some simple feature requests soon.

**Comment by NicolasPetton** [comment]
BTW, I'm planning to add support for kanban boards down the road, similar to what todoist has.
