### ISSUE TITLE
[enhancement] Setting to show completed tasks by default.

### ISSUE THREAD

**Issue by streaml1ne555** [NicolasPetton/Projectify#37]
In a task with subtasks there is an option to show completed subtasks. Would it be possible to either remember the setting to show/hide per task or make a global setting to expand the completed task/subtask list by default?

**Comment by streaml1ne555** [comment]
Hmm looks like it's saving the view choice (it didn't appear to the first time I tested it). So I guess just an option to show completed tasks by default would be nice.

**Comment by NicolasPetton** [comment]
> Would it be possible to either remember the setting to show/hide per task or make a global setting to expand the completed task/subtask list by default?

Good idea, I'll make that customizable in the control panel.
