### ISSUE TITLE
Bug?: Clicking the "todo content" button marks it as done

### ISSUE THREAD

**Issue by diego898** [NicolasPetton/Projectify#39]
As the title says, when I click the todo content button (the little paper), it seems to mark the todo
![Kapture 2021-01-27 at 19 15 47](https://user-images.githubusercontent.com/742407/106075869-15341480-60d4-11eb-8a6e-bec480b33bda.gif)
 complete

**Comment by NicolasPetton** [comment]
hi @diego898, thanks for reporting this.

The bug was also reported in #40 and fixed in 5755764.

I'll make a patch release soon that will include this fix.
