### ISSUE TITLE
Website is slow or non-functional

### ISSUE THREAD

**Issue by ndarilek** [NicolasPetton/Projectify#41]
If I click just about any link off of projectify.wiki--Documentation, for instance--my browser hangs and the page never loads.

I think I recently saw speculation that maybe GH Pages has issues with large HTML files? Wondering if anyone else has experienced this, and if it might be worth migrating to something like Netlify which also has a free tier?

Thanks.

**Comment by NicolasPetton** [comment]
Hi @ndarilek!

I'm not hosting the website on GitHub Pages. Could it have a been a temporary network issue? Are you able to reach https://projectify.wiki/demo.html now for example?

**Comment by ndarilek** [comment]
Hmm, OK, just seems to be super slow. I'm downloading the demo with wget 
and getting 18 KB/Sec. This is on an otherwise fast, unsaturated connection.


Maybe this shouldn't be an issue, and if so then I apologize for opening 
it. But I've been trying to access the demo for days now, and thought I 
saw someone else having issues on Discord recently. I'll open the file 
manually once I've downloaded it.


Thanks.

**Comment by NicolasPetton** [comment]
I've tried from 2 locations (France and the Netherlands), and the download speeds are fine for me.
Could you tell me if other websites hosted on the same network are slow as well, like https://emacs.cafe?

If you could paste the output of a traceroute, that could help as well.

**Comment by NicolasPetton** [comment]
> I saw someone else having issues on Discord recently

Do you know where on Discord? Would you have a link?

**Comment by ndarilek** [comment]
I'll test your other sites a bit later, but here is a link to the person 
who I think may have been having issues: 
https://discord.com/channels/531220230790447154/531221592391417856/801497826612740117 
They were talking about Projectify a couple messages above that, so I 
assume they're having the same issue I am, though mobile was also mentioned.


Thanks.

**Comment by NicolasPetton** [comment]
Thanks for the link to the Discord discussion. I might move the website to another host until I figure out the problem.

**Comment by lfilho** [comment]
Hi Nicolas. First of all thanks for your work :).

Same problem here. That emacs.care website did load normally for me (couple of seconds) but https://projectify.wiki/demo.html  took almost 3 minutes to load:

![image](https://user-images.githubusercontent.com/282756/106322163-4292d680-622a-11eb-89a4-18d2b8b9a8ee.png)

All network stuff was fast as expected, it seems the problem was with the download/transfer itself:

![image](https://user-images.githubusercontent.com/282756/106322408-b0d79900-622a-11eb-8d25-7d7d103e54c9.png)

Here's my traceroute output in any case:

```
traceroute to projectify.wiki (89.234.186.68), 30 hops max, 60 byte packets
 1  _gateway (192.168.1.1)  4.436 ms  4.408 ms  4.398 ms
 2  64-46-15-1.quebec-gw.novuscom.net (64.46.15.1)  6.570 ms  6.561 ms  6.552 ms
 3  v624.core1.yvr1.he.net (64.71.163.117)  6.549 ms  6.540 ms  6.533 ms
 4  100ge0-31.core2.yyc1.he.net (184.105.64.114)  17.950 ms  17.942 ms  17.933 ms
 5  100ge10-2.core1.ywg1.he.net (184.105.222.97)  33.304 ms  33.296 ms  33.288 ms
 6  100ge6-2.core1.tor1.he.net (184.105.64.101)  54.691 ms  49.054 ms  49.037 ms
 7  100ge14-2.core1.nyc4.he.net (184.105.80.9)  59.222 ms  60.133 ms  60.117 ms
 8  100ge14-2.core1.par2.he.net (72.52.92.114)  129.734 ms  129.727 ms  129.719 ms
 9  hivane.par.franceix.net (37.49.236.71)  131.878 ms  131.871 ms  131.864 ms
10  ve487-rt2-th2.bb.hivane.net (193.164.153.194)  131.849 ms  131.842 ms  131.835 ms
11  gw-grifon-th2.bb.hivane.net (193.200.43.86)  143.269 ms  143.262 ms  140.523 ms
12  ovpn01.cogent-rns.bb.grifon.fr (89.234.186.37)  151.134 ms  150.593 ms  150.830 ms
13  * * *
14  * * *
15  * * *
16  * * *
17  * * *
18  * * *
19  * * *
20  * * *
21  * * *
22  * * *
23  * * *
24  * * *
25  * * *
26  * * *
27  * * *
28  * * *
29  * * *
30  * * *
```

**Comment by NicolasPetton** [comment]
@ndarilek @lfilho I've moved the website to another machine (DNS propagation might take a while).
Could you confirm that the download speed issue is fixed?

Thanks,
Nico

**Comment by lfilho** [comment]
Nice. It has loaded in 8s for me. Still a bit slow but if you're still serving it from France I guess that would make sense (I'm in west coast Canada). How about putting it behind a CDN? If you host it in Github Pages you get theirs for free IIRC ;-)

**Comment by NicolasPetton** [comment]
> How about putting it behind a CDN? If you host it in Github Pages you get theirs for free IIRC ;-)

That's indeed tempting, but I usually try to avoid being too dependent on GH's infrastucture.

**Comment by NicolasPetton** [comment]
@ndarilek @lfilho I think we can close this one now. If it's still an issue for you, feel free to reopen it!

**Comment by ndarilek** [comment]
Not sure if I should open a new issue for this, but projectify.wiki is no longer responding for me.

**Comment by NicolasPetton** [comment]
@ndarilek My bad, I'm moving the website to GitHub, it should be back up in a couple of hours.
