### ISSUE TITLE
Demo page, starts to load slow for me. 

### ISSUE THREAD

**Issue by pmario** [NicolasPetton/Projectify#43]
I have to say, I don't have the best download speed, but the demo needs about 3.6 seconds, to show something. 

see:

![grafik](https://user-images.githubusercontent.com/374655/106318629-7db7f880-6270-11eb-90a4-155a6c2c39c1.png)

The first thing I thought: ... Is it possible to tell the server, that it should use "server side compression"?

The other things are:

 - Why do you include _all_ **disabled** translations in the demo?
   - They are not supported atm and only carry weight. 
   - Once language switching is possible, I'd suggest to create a new edition, and tell users that it is huge. 
 - Why do you include the "highlight-plugin" in the demo
   - IMO id doesn't add to the main functionality and it would save about 300kByte
   - empty also contains this plugin. Why?

I would keep the "relink-plugin". IMO it adds to the overall TW functionality!

I could easily strip it down to 2.8 MByte, but ... It still feels too much ... Will have a closer look.

**Comment by NicolasPetton** [comment]
> The first thing I thought: ... Is it possible to tell the server, that it should use "server side compression"?

I thought it was using gzip compression, I'll double-check.

> Why do you include all disabled translations in the demo?
> They are not supported atm and only carry weight.

They're fully working, since they're defined (for now) as regular plugins. Only one can be enabled at the same time though.
I could remove them from the demo page though :+1:.

> Why do you include the "highlight-plugin" in the demo 

Good catch, that's a leftover :-)

**Comment by NicolasPetton** [comment]
> I could remove them from the demo page though

Having the language plugins on the demo page (that also serves as installation instructions) makes it easier to newcomers to install the language plugin of their choice. Removing them only gets the HTML page from 2.9MB down to 2.8MB, so I'll keep them, at least for now.

**Comment by NicolasPetton** [comment]
> I could easily strip it down to 2.8 MByte, but ... It still feels too much ... Will have a closer look.

I got it to 2.9MB. The empty edition from tiddlywiki.com is already 2.4MB, so I don't think this is too bad.

**Comment by NicolasPetton** [comment]
@pmario I've several reports of atrocious download times, so although I could not reproduce it myself, I've moved the website to another machine.

I also removed the highlight plugin from all editions in 6d96f47.

**Comment by pmario** [comment]
>The empty edition from tiddlywiki.com is already 2.4MB, so I don't think this is too bad.

Yea,  I know, that TW5 is much bigger than TWclassic (400kByte). ... The new master branch has the possibility to "uglify" the core code and all the plugins. ... IMO it would be worth a try, to release "user editions" as small as possible. 

Just an idea.

**Comment by pmario** [comment]
I did also have a closer look at the SVGs, that are used. Some of them can be optimized and the size can be reduced by about 50%. .. Some of them .. Do you know: https://jakearchibald.github.io/svgomg/ ?

**Comment by NicolasPetton** [comment]
> > The empty edition from tiddlywiki.com is already 2.4MB, so I don't think this is too bad.
> 
> Yea, I know, that TW5 is much bigger than TWclassic (400kByte). ... The new master branch has the possibility to "uglify" the core code and all the plugins. ... IMO it would be worth a try, to release "user editions" as small as possible.

I'd uglify the source code by default only if that's absolutely necessary, as a lot of the hackability of TiddlyWiki is then lost. Giving the user the choice would be great though.

I've enabled gzip compression, which reduced the transfer to 620KB.

**Comment by pmario** [comment]
>I'd uglify the source code by default only if that's absolutely necessary, as a lot of the hackability of TiddlyWiki is then lost. Giving the user the choice would be great though.

It may be possible with the node-server TW 5.1.24 ... But I didn't test it.

>I've enabled gzip compression, which reduced the transfer to 620KB.

I'm down to less than a second now! .. NICE!
