### ISSUE TITLE
possible bug? filtering todos

### ISSUE THREAD

**Issue by diego898** [NicolasPetton/Projectify#49]
Tying in "this is a test" in the filter tab has the following effect: 

This is a weird corner case, as TW filtering also creates 4 matches, but this tiddler shows them as todos with content. Clicking the content field marks it done (related to a previously reported/fixed bug). 

Question: Is this the function of the filter tab the same as TW default filtering search? 

<img width="689" alt="image" src="https://user-images.githubusercontent.com/742407/106413655-3ec0a900-6410-11eb-951f-e98179f0b30a.png">

**Comment by NicolasPetton** [comment]
Good catch, thanks!

> Question: Is this the function of the filter tab the same as TW default filtering search?

It's using a subfilter, but it is indeed very similar. I'll see if I can find a fix for it.

**Comment by saqimtiaz** [comment]
`[subfilter<todoFilter>tag[todo]sort[title]]`

**Comment by NicolasPetton** [comment]
@saqimtiaz Of course, the subfilter is in the wrong place! Thanks!
