### ISSUE TITLE
Sub-project clarification

### ISSUE THREAD

**Issue by diego898** [NicolasPetton/Projectify#54]
Hey Nico! 

Im a bit confused about a SubProject. There is reference to a SubProject tag, but the demo doesnt have any, and it seems the only way to make one is to manually add that tag. 

Also, dragging a project card into another does not create this tag, but tags one project with the other (does this make it a sub project?)

Projects with a SubProject tag no longer appear in the Dashboard .

The "convert into project" that todos have, removes the actual named project tag, (removes all tags) and just gives it a Project tag. 

Im not sure if any of this is a bug or desired, but I am a bit confused as to the role/purpose and UI of a subproject in projectify.

Thanks!

**Comment by NicolasPetton** [comment]
Hi Diego,

From a todo, you can either:
* convert that todo into a project: 
![2021-02-04-095149](https://user-images.githubusercontent.com/123539/106868144-b885ba80-66ce-11eb-83fe-c0f181e1313c.png)
* Add sub-tasks to that todo (this will keep it as a todo in its current project, but you will be able to add tasks to it):
![2021-02-04-095158](https://user-images.githubusercontent.com/123539/106868261-db17d380-66ce-11eb-944a-7136c8b3ce9f.png)

The second feature adds the tab "SubProject". SubProjects are regular todos in their project, but can have sub-tasks, thus they do not appear in the dashboard (their parent project will, though).

> Also, dragging a project card into another does not create this tag, but tags one project with the other (does this make it a sub project?)

Dragging a project card into another card is not supported, I'm not even sure what it does :)
