### ISSUE TITLE
[RFE] Project Categories

### ISSUE THREAD

**Issue by Tejeev** [NicolasPetton/Projectify#6]
# Request for Enhancement
### What
Categories of projects so that the dashboard can show just the projects of the desired context.

### Details
I'm looking for a way to add my own `Projects` tabs to the dashboard so I can organize the projects by context/category (work, home, garden, etc).  
What might be the best way to go about this?  I was thinking of making copies of `$:/plugins/nico/projectify/ui/dashboard/Projects` that with category names and figuring out how to edit `$:/plugins/nico/projectify/ui/dashboard/InboxAndProjects` to have a drop-down selector for the projects group I want to work on. As I dig in I want to be sure this is the best way and you don't already have something else on the roadmap that I missed.
I'm happy to hack at this a bit to create a pr but would be interested in any pointers or direction you might be able to offer.

Thank you :)

**Comment by Tejeev** [comment]
I was also creating individual inboxes for different projects, but it's not right to add new files to the plugin for each new Project category or inbox for said cat.  Think it would be better to break project/inbox sets out to be generated much like individual projects are tiddlers. Not sure if that makes sense

**Comment by Tejeev** [comment]
Optimally I would be able to drag and drop from the inbox into projects and then later in each project, drag and drop from their own inbox into their sub projects

**Comment by NicolasPetton** [comment]
@Tejeev thanks for the post. Would you mind moving your ideas to the discussion tabs here https://github.com/NicolasPetton/Projectify/discussions? I think it would help keep the GitHub project clean.

**Comment by Tejeev** [comment]
I've not the permissions to do so but I'm happy to move this there.  Sorry I'm used to using issues for RFEs even when they are larger and might need some back and forth.

**Comment by Tejeev** [comment]
I think this could be better thought out in the request anyway, so I'll close the issue and manually rewrite something for discussion.  Thank you @NicolasPetton
