### ISSUE TITLE
[Feature]Calendar begin with Sunday

### ISSUE THREAD

**Issue by Peckystudios** [NicolasPetton/Projectify#71]
Hi 
I really love this tools
Very flexible! 
Thanks for sharing 

the feature that setting Calendar begin with Sunday will make the experience better and good for different  habits people 

Thank you!

**Comment by bepuzzled** [comment]
concur; it's easy to change in the javascript code, but ideally pulled out as a configuration item.

set `firstDay:0` in `$:/plugins/nico/projectify/ui/widgets/date-picker.js`

Big fan of projectify!

**Comment by Peckystudios** [comment]
Thank you! It’s work!

**Comment by NicolasPetton** [comment]
Done in commit 30f8ed0, closing.
